# Generated by Django 4.1.6 on 2023-02-06 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_course_details_date_created_course_outlines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_details',
            name='Course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.course_outlines'),
        ),
    ]
