# Generated by Django 4.1.6 on 2023-02-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_course_details_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enrollment',
            new_name='Enroll',
        ),
    ]
