# Generated by Django 4.1.6 on 2023-02-06 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_enrollment_enroll'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_details',
            old_name='Course',
            new_name='Course_week',
        ),
    ]
