# Generated by Django 4.1.6 on 2023-02-10 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_rename_course_week_course_details_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_details',
            old_name='Course',
            new_name='courseoutlinee',
        ),
    ]
