# Generated by Django 4.1.6 on 2023-02-14 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_rename_course_course_details_courseoutlinee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.course'),
        ),
    ]
