# Generated by Django 4.1.6 on 2023-02-14 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_enroll_course'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enroll',
            unique_together={('student', 'course')},
        ),
    ]
