# Generated by Django 4.1.6 on 2023-02-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_rename_course_quiz_courseoutlines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
