# Generated by Django 4.1.6 on 2023-02-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_alter_questions_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_details',
            name='code_content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='course_details',
            name='image_content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='course_details',
            name='text_content',
            field=models.TextField(null=True),
        ),
    ]
