# Generated by Django 4.1.6 on 2023-02-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_alter_course_details_code_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ImageField(default='Ss', upload_to='courses/image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course_details',
            name='image_content',
            field=models.ImageField(upload_to='course/contentimage'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(upload_to='user/profile_pic'),
        ),
    ]
