# Generated by Django 4.1.6 on 2023-02-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_course_course_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(null=True, upload_to='courses/image'),
        ),
        migrations.AlterField(
            model_name='course_details',
            name='image_content',
            field=models.ImageField(null=True, upload_to='course/contentimage'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='user/profile_pic'),
        ),
    ]
